```{r libs}
library(ribiosUtils)
libordie(BioQC)
libordie(VennDiagram)
```

```{r comp}
load("gtex_signatures.Rdata")
gmtFile = system.file("extdata/exp.tissuemark.affy.roche.symbols.gmt", package="BioQC")
gmt <- readGmt(gmtFile)

intersectSigs = function(sigGmt, sigGtex) {
  gmtGenes = gmt[[sigGmt]]$genes
  gtexGenes = signatures[[sigGtex]]
  return(c(length(gmtGenes), length(gtexGenes), length(intersect(gmtGenes, gtexGenes))))
}

jaccInd = function(sigGmt, sigGtex) {
  is = intersectSigs(sigGmt, sigGtex)
  return(is[3]/(sum(is[1:2]) - is[3]))
}

drawVenn = function(sigGmt, sigGtex) {
  is = intersectSigs(sigGmt, sigGtex)
  plot.new()
  draw.pairwise.venn(is[1], is[2], is[3])
}

jacc.mat = matrix(nrow=length(gmt),ncol=length(signatures),dimnames=list(names(gmt), names(signatures)))

for(i in 1:ncol(jacc.mat)) {
  for(j in 1:nrow(jacc.mat)) {
    jacc.mat[j,i] = jaccInd(names(gmt)[j], names(signatures)[i])
  }
}

jm = melt(jacc.mat)
colnames(jm) = c("BioQC", "GTEx", "jaccard_index")
ord.gtex = hclust(t(dist(jacc.mat)))$ord
ord.bioqc = hclust(dist(jacc.mat))$ord
jm$BioQC = factor(jm$BioQC, levels = rownames(jacc.mat)[ord.bioqc])
jm$GTEx = factor(jm$GTEx, levels = colnames(jacc.mat)[ord.gtex])

hm.palette <- colorRampPalette(rev(brewer.pal(11, 'Spectral')), space='Lab')  


ggplot(jm, aes(x=BioQC, y=GTEx)) + 
  geom_tile(aes(fill=jaccard_index))+
  scale_fill_gradientn(colours = hm.palette(100)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

length.bioqc = unlist(lapply(gmt, function(x) {return(length(x$genes))}))
length.gtex = unlist(lapply(signatures, length))
box.data = rbind(
  data.frame(signature=rep("bioqc", length(length.bioqc)), length=length.bioqc),
  data.frame(signature=rep("gtex", length(length.gtex)), length=length.gtex))

ggplot(box.data, aes(x=signature, y=length)) + geom_boxplot()
qqplot(length.bioqc, length.gtex)
```
